### ISSUE TITLE
Async_ssl memory leak

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/async_ssl#13]
A simple http client using async_ssl seems to rapidly leak memory. You can reproduce the leak by cloning this repo:

https://github.com/rgrinberg/async-ssl-leak

Running `$ make` and then running the python sever followed by `leaker.native`.

**Comment by tari3x** [comment]
Thanks for the report, we are looking into it!

**Comment by tari3x** [comment]
There is a know memory leak that affects async_ssl and has been fixed in 113.43. Would you be able to check if your leak is still present in the development version?

**Comment by trevorsummerssmith** [comment]
@tari3x Would you mind explaining the problem / or sharing the commit that fixes this issue? It's not clear to me from a browsing of the recent commits on master what fixes the issue. Thanks!

**Comment by tari3x** [comment]
Sure, once we can confirm that the issue is actually fixed, I'll describe it here. The fix I'm thinking about was not in async_ssl itself, but rather in [Monitor.try_with].

**Comment by tlubin** [comment]
It appears that the [Monitor.try_with] bug was introduced and subsequently fixed within a single pushed version, so this isn't what was causing problems for @rgrinberg. Can you try adding [Gc.compact] calls to your code and see if it still appears to be leaking memory?

**Comment by rgrinberg** [comment]
I was unable to reproduce this with the latest async/async_ssl after compacting every 100 requests.

thanks @tlubin
