### ISSUE TITLE
Ffi_generated_types not exposed, breaking Async_ssl linking

### ISSUE THREAD

**Issue by avsm** [janestreet/async_ssl#2]
The module is not included in the Async_ssl pack, so linking against Async_ssl always fails at link time.

Fixed it by including Ffi_generated_types in the `_oasis` file, and adding 

```
"lib/ffi_generated_types.cmx": for-pack(Async_ssl)
```

to the `_tags` file.

**Comment by avsm** [comment]
Can't really workaround this one easily aside from marking the whole package broken.  Is there an ETA on a fix or should I do that ?

**Comment by trefis** [comment]
I'll update the package and send a PR on opam later today.
Sorry for the delay!

**Comment by avsm** [comment]
That's great, thanks -- just knowing a rough eta is helpful

**Comment by trefis** [comment]
Thanks for the fix!
I'm actually holding off on the opam-package update though because I'd like to resolve #3 before doing another minor release.
Hopefully this can be resolved today/tomorrow, otherwise I'll do a minor release with only the fix of this issue tomorrow.
