### ISSUE TITLE
dependency on nonexistent ctypes version

### ISSUE THREAD

**Issue by thedufer** [janestreet/async_ssl#29]
At master async_ssl won't install because of the required version of ctypes:

```
$ opam upgrade async_ssl
The following dependencies couldn't be met:
  - async_ssl → ctypes = 0.14.0+dynamicfunptrtype
      no matching version
```

I'm not sure what "+dynamicfunptrtype" is supposed to signify, but opam doesn't seem to know what to do with it.

**Comment by hhugo** [comment]
@xclerc, can you take a look at this ?

**Comment by xclerc** [comment]
The offending package is defined [here](https://github.com/janestreet/opam-repository/tree/external-packages/packages).
It should be enough to add the repository to opam, through: 

    opam repository add js https://github.com/janestreet/opam-repository.git

Please let me know if that does not fix your problem.

**Comment by thedufer** [comment]
Ah, I was using https://ocaml.janestreet.com/opam-repository as suggested at https://github.com/janestreet/opam-repository, which from that readme is a mirror of the github repo you suggested, plus static tarballs.  Perhaps the mirror is not being kept fully up-to-date and that readme should suggest using the GItHub repo directly instead?

**Comment by hhugo** [comment]
@xclerc, the package is not available on the `master` branch, it only exists on branches `external-packages` and `add-ctypes-with-dynamicfunptrtype`. Is that expected ?

**Comment by xclerc** [comment]
@hhugo My bad, the command line should indeed be something like:

    opam repository add js https://github.com/janestreet/opam-repository.git#external-packages

I am unsure whether we want to have this kind of definition in master,
but "add-ctypes-with-dynamicfunptrtype" was the feature branch merged
into "external-packages" (I just deleted it).

**Comment by copy** [comment]
This was fixed in https://github.com/ocaml/opam-repository/pull/15759

**Comment by xclerc** [comment]
Indeed, thanks for the reminder.
