### ISSUE TITLE
v0.13.0 is not on opam

### ISSUE THREAD

**Issue by kittipatv** [janestreet/async_ssl#30]
I see there is a branch for v0.13.0 but it looks like it wasn't published to opam. Installing this package required downgrading Core to v0.12.0. Is there any reason not to publish v0.13.0?

**Comment by hanw** [comment]
v0.13.0 depends on this fix: https://github.com/ocamllabs/ocaml-ctypes/pull/595, which was just merged to master recently.

**Comment by kit-ty-kate** [comment]
On an extra note this is also a requirement to be able to install this package on OCaml 4.10. cc @xclerc

**Comment by xclerc** [comment]
`async_ssl` needs to be adapted because `ctypes.0.16.0` is slightly
different from the original proposal in https://github.com/ocamllabs/ocaml-ctypes/pull/595.
The changes are currently reviewed internally.

**Comment by yminsky** [comment]
Is the plan to backport these changes, so we can get a 0.13.0-compatible version?

**Comment by xclerc** [comment]
Yes, that's the plan.

**Comment by xclerc** [comment]
I have just opened https://github.com/ocaml/opam-repository/pull/15759 to release v0.13.0 in opam.

**Comment by xclerc** [comment]
https://github.com/ocaml/opam-repository/pull/15759 has been merged, and I have
just checked on a fresh opam switch that one can indeed
install v0.13.0.
