### ISSUE TITLE
ERROR while compiling async_ssl

### ISSUE THREAD

**Issue by Zhang-WJ** [janestreet/async_ssl#38]
![Jietu20230913-114907](https://github.com/janestreet/async_ssl/assets/37130869/ba4fc8d1-e034-4110-905b-9b08ed40c005)
When run opam install bonsai,  meet this error

**Comment by tiash** [comment]
Thank you for this report. Fix is in the pipe and should hopefully land in the next days (there's a missing include)

**Comment by dkalinichenko-js** [comment]
Fixed.
