### ISSUE TITLE
Read/write comments mixed up?

### ISSUE THREAD

**Issue by eatonphil** [janestreet/async_ssl#4]
I was reading through ffi.ml and got confused at lines [80 and 88](https://github.com/janestreet/async_ssl/blob/master/lib/ffi.mli#L80-L93). Shouldn't these two lines be swapped? I.e.:

  (** Read some bytes from a BIO.
      Returns either the amount of data successfully read (if the return value is
      positive) or that no data was successfully read if the result is 0 or -1.  If the
      return value is -2 then the operation is not implemented in the specific BIO
      type. *)
  val read : t -> buf:(char ptr) -> len:int -> int

  (** Write some bytes to a BIO.
      Returns either the amount of data successfully written (if the return value is
      positive) or that no data was successfully written if the result is 0 or -1.  If the
      return value is -2 then the operation is not implemented in the specific BIO
      type. *)

If these were actually swapped, I can submit a pull request. If not, could someone explain what it means?

**Comment by bmillwood** [comment]
I'm betting it's a typo. I've fixed it internally and it should be released with the next public release (or possibly the one after).

**Comment by eatonphil** [comment]
Awesome, thanks!
