### ISSUE TITLE
fix a camlp4 version of sexplib on osx?

### ISSUE THREAD

**Issue by avsm** [janestreet/async_ssl#9]
I'm trying to port various camlp4 sexplib users over to the new ppx version, and the problem is that the older async_ssl is broken on OSX.  As a one-off, would it be possible to backport the build fixes to the last camlp4 version? That will really help jump over the conflict chasm...

This is a slightly odd request I realise :)

**Comment by diml** [comment]
Sure, I submitted a minor release: ocaml/opam-repository#5517
